/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek.part.pkg2;



import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import java.util.StringTokenizer;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ADMIN
 */
public class NewJFrame_master extends javax.swing.JFrame {

    JTable table;
    DefaultTableModel model;
    Object []columnName;
    String[][] data;
    int row, col;
    int rowCount, colCount;
    
    
    /**
     * Creates new form NewJFrame_master
     */
    public NewJFrame_master() {
        initComponents();
        
        
    }
    
     public static String IntToLetter(int Int) {
    if (Int<27){
      return Character.toString((char)(Int+96));
    } else {
      if (Int%26==0) {
        return IntToLetter((Int/26)-1)+IntToLetter(((Int-1)%26+1));
      } else {
        return IntToLetter(Int/26)+IntToLetter(Int%26);
      }
    }
  }
    
     private void tableSetting(int col, int row){
        
        
        
        data = new String[row][col+1];
        columnName = new Object[col+1];

         for (int i = 0; i <= col; i++) {
             if(i==0){
                 columnName[i]="";
             }
             else if(i<=26){
                 columnName[i] = Character.toString((char) (i+64));
             }
             else if(i>=27){
                 columnName[i] =  IntToLetter(i).toUpperCase();
             }
         }
        
         for (int i = 0; i <row; i++) {
            for (int j = 0; j <=col; j++) {
                data[i][j]="";
            }
        }
         
        for (int i = 0; i <row; i++) {
            for (int j = 0; j <=col; j++) {
                
                if(j==0){
                    data[i][j]=(i+1)+"";
                }
            }
        }
        
       
    }
    
    public void loadTable(){
        
        model = new DefaultTableModel(data, columnName);
        table = new JTable(model);
        

        jTable_bilangan.setModel(model);
        
    }
    
    public void concat( int row1, int col1, int row2, int col2 ){
        String temp1 = jTable_bilangan.getValueAt(row1, col1)+"";
        String temp2 = jTable_bilangan.getValueAt(row2, col2)+"";
        String hasil = temp1 + temp2;
        
        
        for (int j = 1; j <= colCount; j++) {
            for (int i = 0; i < rowCount; i++) {
                if(i==row && j==col){
                    data[i][j]=hasil;
                }
            }
        }
        
    }
    
    public static boolean isOperator (char c){
        return c == '+' || c=='-' || c=='*' || c=='/' || c=='^';
    }
    
    public static int postfixHierarchy( char ch){
        
            switch (ch)
            {        
                             
        case '+':
        case '-':
            return 1;
      
        case '*':
        case '/':
            return 2;
      
        case '^':
            return 3;
        }
        
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_bilangan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSpinner_col = new javax.swing.JSpinner();
        jSpinner_row = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jButton_apply = new javax.swing.JButton();
        jButton_loadTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_bilangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_bilangan.setToolTipText("");
        jTable_bilangan.setRowSelectionAllowed(false);
        jTable_bilangan.getTableHeader().setReorderingAllowed(false);
        jTable_bilangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_bilanganMouseClicked(evt);
            }
        });
        jTable_bilangan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_bilanganKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_bilangan);

        jLabel1.setText("Ukuran : ");

        jLabel2.setText("x");

        jButton_apply.setText("Apply");
        jButton_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_applyActionPerformed(evt);
            }
        });

        jButton_loadTable.setText("LOAD TABLE");
        jButton_loadTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loadTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_apply)
                        .addGap(208, 208, 208)
                        .addComponent(jButton_loadTable))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner_col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner_col, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner_row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_apply))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton_loadTable)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_applyActionPerformed
        // TODO add your handling code here:
        this.colCount = Integer.parseInt(jSpinner_col.getValue().toString());
        this.rowCount = Integer.parseInt(jSpinner_row.getValue().toString());
        tableSetting(colCount, rowCount);
        loadTable();
    }//GEN-LAST:event_jButton_applyActionPerformed

    private void jTable_bilanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_bilanganMouseClicked
        // TODO add your handling code here:
        if(row!=-1 && col!=-1){
            String value = (String) jTable_bilangan.getValueAt(row, col);
        
            if(!value.isEmpty()){
                 data[row][col]= (String) jTable_bilangan.getValueAt(row, col);
                 
            }
        }
        
        for (int j = 1; j <=colCount; j++) {
            for (int i = 0; i < rowCount; i++) {
                data[i][j]= jTable_bilangan.getValueAt(i, j).toString();
            }
        }
        System.out.println(row + " "+col);
    }//GEN-LAST:event_jTable_bilanganMouseClicked

    private void jTable_bilanganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_bilanganKeyReleased
        // TODO add your handling code here:
        this.row = jTable_bilangan.getSelectedRow();
        this.col = jTable_bilangan.getSelectedColumn();
        String sintax = "";
        String expression = (String) jTable_bilangan.getValueAt(row, col);
        char idx_0 = 0;
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if(!expression.isEmpty()){
                idx_0 = expression.charAt(0);
            }
            
            Stack<String> st = new Stack();
            st.push("$");
            for(int i = 0;i<expression.length();i++){
                char temp = expression.charAt(i);
                if(temp!='('){
                    st.push(temp+"");
                }else{
                    break;
                }
            }
            while(!st.peek().equals("$")){
                String param = st.pop();
                sintax = param + sintax;
            }
            //System.out.println("sintax : " + sintax);
        
        }
        if(sintax.equalsIgnoreCase("=concat")){
            Stack<String> st = new Stack();
            int startKurung = 0;
            st.push("$");
            for(int i = 0;i<expression.length();i++){
                char temp = expression.charAt(i);
                if(temp=='('){
                    startKurung = i + 1;
                    break;
                }
            }
            while(expression.charAt(startKurung)!=')'){
                char temp = expression.charAt(startKurung);    
                st.push(temp+"");
                startKurung = startKurung + 1;
            }
            
            int row2 = 0;
            String col2;
            row2 = Integer.parseInt(st.pop())-1;
            col2 = st.pop();
            
            st.pop();
            
            int row1 = 0;
            String col1;
            row1 = Integer.parseInt(st.pop())-1;
            col1 = st.pop();
            
            char ke2 = col2.charAt(0);
            char ke1 = col1.charAt(0);
            
            int kolomke1 = ke1;
            kolomke1 = kolomke1-64;
            int kolomke2 = ke2;
            kolomke2 = kolomke2-64;

            concat(row1,kolomke1,row2,kolomke2);
            loadTable();
            }
        else if (sintax.equalsIgnoreCase("=left")){
            Stack<String> st = new Stack();
            int startKurung = 0;
            st.push("$");
            for(int i = 0;i<expression.length();i++){
                char temp = expression.charAt(i);
                if(temp=='('){
                    startKurung = i + 1;
                    break;
                }
            }
            while(expression.charAt(startKurung)!=')'){
                char temp = expression.charAt(startKurung);    
                st.push(temp+"");
                startKurung = startKurung + 1;
            }
            int row = 0;
            String col;
            row = Integer.parseInt(st.pop())-1;
            col = st.pop();
            char kol = col.charAt(0);
            int kolom = kol;
            kolom = kolom-64;
            char left = jTable_bilangan.getValueAt(row, kolom).toString().charAt(0);
            for (int j = 1; j <= colCount; j++) {
                         for (int i = 0; i < rowCount; i++) {
                            if(j==this.col && i==this.row)
                                data[i][j]=left+"";
                        }
                    }
            loadTable();
            }
        else if (sintax.equalsIgnoreCase("=right")){
            Stack<String> st = new Stack();
            int startKurung = 0;
            st.push("$");
            for(int i = 0;i<expression.length();i++){
                char temp = expression.charAt(i);
                if(temp=='('){
                    startKurung = i + 1;
                    break;
                }
            }
            while(expression.charAt(startKurung)!=')'){
                char temp = expression.charAt(startKurung);    
                st.push(temp+"");
                startKurung = startKurung + 1;
            }
            int row = 0;
            String col;
            row = Integer.parseInt(st.pop())-1;
            col = st.pop();
            char kol = col.charAt(0);
            int kolom = kol;
            kolom = kolom-64;
            String executedString =jTable_bilangan.getValueAt(row, kolom).toString();
            char right = executedString.charAt(executedString.length()-1);
            for (int j = 1; j <= colCount; j++) {
                         for (int i = 0; i < rowCount; i++) {
                            if(j==this.col && i==this.row)
                                data[i][j]=right+"";
                        }
                    }
            loadTable();
            }
        else if(sintax.equalsIgnoreCase("=mid")){
            Stack<String> st = new Stack();
            int startKurung = 0;
            st.push("$");
            for(int i = 0;i<expression.length();i++){
                char temp = expression.charAt(i);
                if(temp=='('){
                    startKurung = i + 1;
                    break;
                }
            }
            while(expression.charAt(startKurung)!=')'){
                char temp = expression.charAt(startKurung);    
                st.push(temp+"");
                startKurung = startKurung + 1;
            }
            int row = 0;
            String col;
            row = Integer.parseInt(st.pop())-1;
            col = st.pop();
            char kol = col.charAt(0);
            int kolom = kol;
            kolom = kolom-64;
            String executedString =jTable_bilangan.getValueAt(row, kolom).toString();
            char mid = executedString.charAt(executedString.length()/2);
            for (int j = 1; j <= colCount; j++) {
                         for (int i = 0; i < rowCount; i++) {
                            if(j==this.col && i==this.row)
                                data[i][j]=mid+"";
                        }
                    }
            loadTable();
            }
        else if (sintax.equalsIgnoreCase("=sum")){
            try {
            
                Stack<String> st = new Stack();
            int startKurung = 0;
            st.push("$");
            for(int i = 0;i<expression.length();i++){
                char temp = expression.charAt(i);
                if(temp=='('){
                    startKurung = i + 1;
                    break;
                }
            }
            while(expression.charAt(startKurung)!=')'){
                char temp = expression.charAt(startKurung);    
                st.push(temp+"");
                startKurung = startKurung + 1;
            }
            
            int row2 = 0;
            String col2;
            row2 = Integer.parseInt(st.pop())-1;
            col2 = st.pop();
            
            st.pop();
            
            int row1 = 0;
            String col1;
            row1 = Integer.parseInt(st.pop())-1;
            col1 = st.pop();
            
            char ke2 = col2.charAt(0);
            char ke1 = col1.charAt(0);
            
            int kolomke1 = ke1;
            kolomke1 = kolomke1-64;
            int kolomke2 = ke2;
            kolomke2 = kolomke2-64;
            Queue<Float> queue = new LinkedList<>();
            float hasil=0;

            for (int j = 1; j <=colCount; j++) {
            
             
            for (int i = 0; i < rowCount; i++) {

                
                if(i>=row1 && i <=row2 && j==kolomke1 ){
                    if(!jTable_bilangan.getValueAt(i, j).toString().equals("")){
                        queue.add(Float.parseFloat(jTable_bilangan.getValueAt(i, j).toString()));
                    }
                }   
            }
            }
            Iterator<Float> itr = queue.iterator();
            
                    
                    
                    while(itr.hasNext()){
                        hasil+=itr.next();
                        
                    }
                    
                    data[this.row][this.col]=hasil+"";
                    
              
            loadTable();
            }
            catch(Exception e) {
              data[this.row][this.col]=0+"";
              loadTable();
            }
            
            
            
        }
        else if( sintax.equalsIgnoreCase("=average")){
            try {
                
            Stack<String> st = new Stack();
            int startKurung = 0;
            st.push("$");
            for(int i = 0;i<expression.length();i++){
                char temp = expression.charAt(i);
                if(temp=='('){
                    startKurung = i + 1;
                    break;
                }
            }
            while(expression.charAt(startKurung)!=')'){
                char temp = expression.charAt(startKurung);    
                st.push(temp+"");
                startKurung = startKurung + 1;
            }
            
            int row2 = 0;
            String col2;
            row2 = Integer.parseInt(st.pop())-1;
            col2 = st.pop();
            
            st.pop();
            
            int row1 = 0;
            String col1;
            row1 = Integer.parseInt(st.pop())-1;
            col1 = st.pop();
            
            char ke2 = col2.charAt(0);
            char ke1 = col1.charAt(0);
            
            int kolomke1 = ke1;
            kolomke1 = kolomke1-64;
            int kolomke2 = ke2;
            kolomke2 = kolomke2-64;
            Queue<Float> queue = new LinkedList<>();

            
            for (int j = 1; j <=colCount; j++) {
            
            
            
            for (int i = 0; i < rowCount; i++) {
            
                
                if(i>=row1 && i <=row2 && j==kolomke1 ){
                    if(!jTable_bilangan.getValueAt(i, j).toString().equals("")){
                        queue.add(Float.parseFloat(jTable_bilangan.getValueAt(i, j).toString()) );
                    }
                    data[i][j]=jTable_bilangan.getValueAt(i, j).toString();
                }
                
                
            }
            
        }
            Iterator<Float> itr = queue.iterator();
            float hasil =0;
                    
                    
                    while(itr.hasNext()){
                        hasil+=itr.next();
                        
                    }
                    hasil = hasil/(row2-row1+1);
                    data[this.row][this.col]=hasil+"";
               
        loadTable();
}
catch(Exception e) {
        data[this.row][this.col]=0+"";
        loadTable();
}
            
        }
        else if (idx_0=='='){
            Stack<Character> stack = new Stack<>();
            String postfix="";
            char c;
             for (int i = 1; i < expression.length(); i++) {
                c=expression.charAt(i);
                if(i<expression.length()-1 && Character.isLetter(c)){
                    if(Character.isDigit(expression.charAt(i+1))){
                        int row = 0;
                    String col;
                    col = Character.toString(c);
                    row = Integer.parseInt(Character.toString((char)(expression.charAt(i+1))))-1;
                    char ke2 = col.charAt(0);
                    int kolom = ke2;
                    kolom = kolom-64;
                    float operand = Float.parseFloat(jTable_bilangan.getValueAt(row, kolom).toString());
                    postfix+=operand+" ";
                    }
                    
                }
                else {
                    if(c=='(') {
                    stack.push('(');
                    }
                    else if(c==')'){
                        
                        while(!stack.isEmpty() && stack.peek()!='('){
                        postfix+=stack.pop()+" ";
                        }
                        stack.pop();
                    }
                    else if(isOperator(c)) {
                       
                        while(!stack.isEmpty()&& postfixHierarchy(c)<postfixHierarchy(stack.peek())){
                            postfix+=stack.pop() + " ";
                        }
                        stack.push(c);
                    }
                }
            }
             while(!stack.isEmpty()){
                    postfix+=stack.pop()+ " ";
                }
             Stack<Float> calc = new Stack();
            StringTokenizer st = new StringTokenizer(postfix);
     while (st.hasMoreTokens()) {
      String token = st.nextToken();
    float x = 0;
    float y = 0;
    float r = 0;
    
    if(token.equals("+")){
        x = calc.pop();
        y = calc.pop();
        r = x+y;
        calc.push(r);
    }
     else if(token.equals("-")){
        x = calc.pop();
        y = calc.pop();
        r = x-y;
        calc.push(r);
    }
     else if(token.equals("*")){
        x = calc.pop();
        y = calc.pop();
        r = x*y;
        calc.push(r);
    }
     else if(token.equals("/")){
        x = calc.pop();
        y = calc.pop();
        r = x/y;
        calc.push(r);
    }
    else if(token.equals("^")){
        x = calc.pop();
        y = calc.pop();
        r = (int) Math.pow(x, y);
        calc.push(r);
    }
    else{
       float t = Float.parseFloat(token);
        calc.push(t);
    }
}
 
 float a = calc.pop();
 data[this.row][this.col]=a+"";
            loadTable();
            }
            
                
               
          
                
                
            
            
        
        for (int j = 1; j <=colCount; j++) {
            for (int i = 0; i < rowCount; i++) {
                data[i][j]=jTable_bilangan.getValueAt(i, j).toString();
            }
        }
        
        
        
        System.out.println(row + " "+col);
    }//GEN-LAST:event_jTable_bilanganKeyReleased

    private void jButton_loadTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loadTableActionPerformed
        // TODO add your handling code here:
        loadTable();
    }//GEN-LAST:event_jButton_loadTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_master().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_apply;
    private javax.swing.JButton jButton_loadTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_col;
    private javax.swing.JSpinner jSpinner_row;
    private javax.swing.JTable jTable_bilangan;
    // End of variables declaration//GEN-END:variables
}
